#!/bin/bash

overlay=/usr/share/pixmaps/lockoverlay.png

scrot /tmp/currentworkspace.png
convert /tmp/currentworkspace.png -blur 0x5 /tmp/currentworkspaceblur.png
composite -gravity SouthWest /home/werdiens/Downloads/pngegg.png /tmp/currentworkspaceblur.png /tmp/lockbackground.png
i3lock -i /tmp/lockbackground.png
